name: Build C++ Project in Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # 添加 repository_dispatch 事件作为触发器
  repository_dispatch:
    # (可选) 指定只响应特定的事件类型
    types: [ triggered-by-repo-a-update ]   

jobs:
  build:
    name: Build with Docker on Self-hosted Runner
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Generate timestamp
        id: gen_time
        run: echo "ts=$(date +'%Y%m%d_%H%M%S')" >> "$GITHUB_OUTPUT"
      - name: Checkout repository to dynamic path
        uses: actions/checkout@v4
        with:
          path: my-code-${{ steps.gen_time.outputs.ts }}      
      - name: Get repo name only
        id: get_repo
        run: |
          REPO_NAME=$(basename "${{ github.repository }}")
          echo "repo_name=$REPO_NAME" >> "$GITHUB_OUTPUT"
      - name: Build inside Docker and output artifact
        run: |
          export SRC_DIR="${GITHUB_WORKSPACE}/my-code-${{ steps.gen_time.outputs.ts }}"
          export OUTPUT=${{ vars.OUTPUT_DIR }}/${{ steps.get_repo.outputs.repo_name }}/${{ github.ref_name }}
          export OUTPUT_DIR=${{ vars.OUTPUT_DIR }}/${{ steps.get_repo.outputs.repo_name }}/master
          export CLIENT_REPO_NAME="${{ github.event.client_payload.repo_name }}"
          export CLIENT_REF="${{ github.event.client_payload.ref }}"
          export LIB_DIR="${OUTPUT_DIR}/${CLIENT_REPO_NAME:-flatbuffers}/${CLIENT_REF:-master}/"
          mkdir -p "${OUTPUT_DIR}"        
          mkdir -p "${SRC_DIR}/build"        
          docker run --rm \
            -v "${SRC_DIR}:/workspace" \
            -v "${OUTPUT_DIR}:/output" \
            -v "${LIB_DIR}:/custom_lib" \
            -w	/workspace \
            --entrypoint bash davidwu-base-gcc:1.0  -c "
              cd cpp &&
              mkdir -p build &&
              cd build &&
              cmake -DARROW_FLATBUFFERS=ON -DFLATBUFFERS_HOME=/output -DCMAKE_CXX_FLAGS="-I/custom_lib" -DCMAKE_INSTALL_PREFIX=/output .. &&
              cmake --build . -- -j70 &&
              cmake --install . &&
              chmod -R 777 /output/* &&
              echo "key,value" > /output/csv/system.csv &&
              echo "os_version,$(source /etc/os-release && echo "${ID}:${VERSION_ID}")" >> /output/csv/system.csv &&
              echo "cmake_version,$(cmake --version | head -n1 | awk '{print $3}')" >> /output/csv/system.csv &&
              echo "gcc_version,$(g++ -dumpfullversion)" >> /output/csv/system.csv &&
              echo done"
      - name: Get latest commit message
        id: get_commit_msg
        run: |
          msg=$(git -C my-code-${{ steps.gen_time.outputs.ts }} log -1 --pretty=%B)
          echo "message=$msg" >> "$GITHUB_OUTPUT" 
      - name: Generate hash and build info CSV
        run: |
          export OUTPUT_DIR=${{ vars.OUTPUT_DIR }}/${{ steps.get_repo.outputs.repo_name }}/${{ github.ref_name }}
          HASH_FILE="${OUTPUT_DIR}/hashes.csv"          
          BUILD_INFO_FILE="${OUTPUT_DIR}/build_info.csv"
          {
            echo "key,value"
            echo "repo_name,${{ github.repository }}"
            echo "commit_msg,${{ steps.get_commit_msg.outputs.message }}"
            echo "commit_tag,${{ github.ref }}"
            echo "branch,${{ github.ref_name }}"
            echo "commit_hash,${{ github.sha }}"
            echo "actor,${{ github.actor }}"
            echo "event_name,${{ github.event_name }}" 
            echo "image_name,davidwu-base-gcc" 
            echo "image_hash,a2e1c068baa8" 
            echo "mount_path,${OUTPUT_DIR}"
          } > "$BUILD_INFO_FILE"
          echo "filename,sha256" > "$HASH_FILE"
          find "${OUTPUT_DIR}" -type f -executable | while read file; do
            hash=$(sha256sum "$file" | awk '{print $1}')
            rel_path="${file#${OUTPUT_DIR}/}"
            echo "${rel_path},${hash}" >> "$HASH_FILE"
          done
          echo "✅ Hash CSV generated at: ${HASH_FILE}"
          cat "$HASH_FILE"
          echo "✅ build info CSV generated at: ${BUILD_INFO_FILE}"
          cat "$BUILD_INFO_FILE"
      - name: Clean up work directory
        run: |
          export SRC_DIR="${GITHUB_WORKSPACE}/my-code-${{ steps.gen_time.outputs.ts }}"
          echo "${SRC_DIR}/build"  # 清理工作目录
          # rm -rf ${SRC_DIR}/build/*  # 清理工作目录